apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-ns
spec:
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30090
  type: NodePort
